import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../context/AuthContext";
import { ProductProvider } from "@/context/ProductContext";


import NavbarView from "../components/navbar/NavbarView";
import Footer from "../components/footer/Footer";
import BadgeWhatsapp from "../components/badgeWhatsapp/BadgeWhatsapp";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';


const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Henry Shop",
  description: "Generated by MarcosotolaDev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
      <ProductProvider>
      <body className={`${inter.className} h-screen flex flex-col justify-between`}>
        <NavbarView />
        <main>{children}</main>
        <Footer />
        <BadgeWhatsapp />
        <ToastContainer />
      </body>
      </ProductProvider>
      </AuthProvider>
    </html>
  );
}
